---
  credentials:
    source_profile: 'default'
    iam_role: 'arn:aws:iam::1234567890:role/myrole'
  aws:
    account_id: '1234567890'
    region: 'ap-southeast-2'
    availability_zone: 'ap-southeast-2a'
  ec2:
    local_ipv4: '127.0.0.1'
    instance_id: 'i-xx-instance-id-xx'
    image_id: 'i-xx-image-id-xx'
    instance_type: 't3.nano'
    architecture: 'x86_64'
    hostname: 'ec2-hostname'
